version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
    versioning-strategy: lockfile-only
    open-pull-requests-limit: 5
    groups:
      python-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      frontend-minor-patch:
        update-types: [minor, patch]
    ignore:
      - dependency-name: typescript
        update-types: ["version-update:semver-major"]

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: tuesday
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: tuesday
    groups:
      github-actions:
        patterns: ["*"]
    open-pull-requests-limit: 1

  - package-ecosystem: terraform
    directory: /infra/aws/terraform
    schedule:
      interval: weekly
      day: tuesday
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: hashicorp/aws
        update-types: ["version-update:semver-major"]
